version: '2'

services:
  nginx:
    build: ./nginx
    image: scannerresearch/esper-nginx
    volumes:
      - ./esper:/usr/src/app
    depends_on:
      - esper
    ports:
      - "80:80"

  esper:
    build:
      context: ./esper
      args:
        https_proxy: "${https_proxy}"
    image: scannerresearch/esper
    volumes:
      - ./esper:/usr/src/app
    depends_on:
      - db
    expose:
      - "8000"
    environment:
      # Local DB settings
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PASSWORD=${MYSQL_PASSWORD}
      - DJANGO_DB_USER=root
      # Cloud DB settings. Uncomment these and comment the above to use Cloud SQL.
      # - DJANG_DB_HOST=104.197.78.40
      # - DJANGO_DB_USER=will

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=esper
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - ./mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
