[google]
project = "visualdb-1046"
zone = "us-east1-d"
base_image_name = "esper-base"

[storage]
type = "google"
bucket = "esper"
path = "public"

[database]
# type = "local"
type = "google"
name = "esper-dev"
user = "will"
password = "foobar"

[compute]
gpu = false
