[google]
project = "visualdb-1046"
zone = "us-west1-b"

[storage]
type = "google"
bucket = "esper"
path = "public"

[database]
type = "google"
name = "esper-public-dev"
user = "will"
password = "foobar"

[compute]
gpu = true
