[storage]
type = "local"       # Video/image files stored on the local machine
path = "/var/esper"  # Currently unused, ignore

[database]
type = "local"       # Database is stored/run locally
user = "will"        # Username
password = "foobar"  # Password

[compute]
gpu = false          # Whether or not you have a GPU on the local machine
